name: simple CI workflow
on: [push]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v4

       - name: run a hello world script
         run: echo "hello github actions is working"
  
